import dotenv from 'dotenv';
dotenv.config();
import OpenAI from "openai";

const dalle = async (m, Matrix) => {
  try {
  const command = m.body.split(' ')[0].toLowerCase();
  const prompt = m.body.substring(command.length).trim();
  if (command == 'imagine') {
    const openai = new OpenAI({ apiKey: process.env.OPENAI_AI_API_KEY });
    await m.React('⏳');
    const { key } = await Matrix.sendMessage(m.from, { text: 'Generating Image please wait...' }, {quoted: m});
    const response = await openai.images.generate({
       model: "dall-e-3",
       prompt: prompt,
       n: 1,
       size: "1024x1024",
    });
    await m.React('✅');
    await m.wait('✅ Sucsessfully Generated', key);
    await Matrix.sendMessage(m.from, {
      image: {
        url: response.data[0].url,
      },
      caption: "✅ Generated by OpenAI's Dall-E 3",
    }, {
      quoted: m,
    });
  }} catch (err) {
    console.log(err)
    Matrix.sendMessage(m.from, { text: Something Went Erroring... }, {quoted: m});
  }
}

export default dalle;